[package]
name = "jsonnet-bridge"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
rust2go = { version = "0.4.0" }
regex = { workspace = true }
lsp-server = { workspace = true }
strum.workspace = true
language-server = { path = "../language-server"}
jsonnet-location = { path = "../jsonnet-location"}
grustonnet-config = { path = "../grustonnet-config/"}
anyhow.workspace = true

[build-dependencies]
rust2go = { version = "0.4.0", features = ["build"] }
rust2go-cli = "0.4.2"
sha2 = "0.11.0"
