[package]
name = "grustonnet-config"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
lsp-types = { workspace = true, features = ["proposed"] }
smart-default = "0.7.1"
schemars = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
serde_with = "3.16.1"
