[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
uninlined_format_args = "allow"
needless_update = "allow"
unwrap_used = "warn"

[workspace.lints.rust]
missing_docs = "allow"

[workspace]
members = [
"crates/grustonnet-bin",
"crates/grustonnet-lint",
"crates/grustonnet-debugger",
"crates/rust-dap",
"crates/grustonnet-ls-lib",
"crates/jsonnet-bridge",
"crates/jsonnet-location",
"crates/language-server",
"crates/test-macros",
"crates/utils",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.98"
