[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.lints.clippy]
uninlined_format_args = "allow"
needless_update = "allow"
unwrap_used = "warn"

[workspace.lints.rust]
missing_docs = "allow"

[profile.release]
strip = true
lto = true

[workspace]
members = [
"crates/grustonnet-bin",
"crates/grustonnet-lint",
"crates/grustonnet-debugger",
"crates/rust-dap",
"crates/grustonnet-ls-lib",
"crates/jsonnet-bridge",
"crates/jsonnet-location",
"crates/language-server",
"crates/test-macros",
"crates/version-macros",
"crates/utils",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.98"
crossbeam = "0.8.4"
bincode-next = "2.1.0"
clap = "4.5.40"
env_logger = "0.11.8"
htmd = "0.5.0"
itertools = "0.15.0"
log = "0.4.27"
lsp-server = "0.10.0"
lsp-types = "0.97.0"
pretty_assertions = "1.4.1"
quote = "1.0.20"
rayon = "1.10.0"
regex = "1.11.1"
ropey = "1.6.1"
schemars = "1.0.1"
serde = "1.0.219"
serde_json = "1.0.140"
syn = "3.0.0"
tokio = "1.45.1"
tracy-client = "0.18.2"
tree-sitter = "0.26.0"
walkdir = "2.5.0"
url = "2.5.8"
utils = { path = "crates/utils"}
strum = { version = "0.28.0", features = ["derive", "strum_macros"] }
