[package]
name = "rust-dap"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
crossbeam.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
lsp-server = { workspace = true }
anyhow.workspace = true
log = { workspace = true }
