package main

/*
// Generated by rust2go. Please DO NOT edit this C part manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ListRef {
  const void *ptr;
  uintptr_t len;
} ListRef;

typedef struct StringRef {
  const uint8_t *ptr;
  uintptr_t len;
} StringRef;

typedef struct ASTInfoRef {
  struct ListRef ast_data;
  struct StringRef error_data;
} ASTInfoRef;

typedef struct EvaluateParamsRef {
  struct ListRef ext_vars;
  struct ListRef ext_code;
  struct ListRef jpaths;
} EvaluateParamsRef;

typedef struct ExtValueRef {
  struct StringRef name;
  struct StringRef value;
} ExtValueRef;

typedef struct FormatOptionsRef {
  int32_t indent;
  int32_t max_blank_lines;
  int32_t string_style;
  int32_t comment_style;
  bool pretty_field_names;
  bool pad_arrays;
  bool pad_objects;
  bool sort_imports;
  bool use_implicit_plus;
  bool strip_everything;
  bool strip_comments;
  bool strip_all_but_comments;
} FormatOptionsRef;

typedef struct StringInfoRef {
  struct StringRef data;
  struct StringRef error;
} StringInfoRef;

typedef struct TestDataRef {
  struct StringRef name;
  struct ListRef data;
} TestDataRef;
*/
import "C"
import (
	"runtime"
	"unsafe"

	"github.com/ihciah/rust2go/asmcall"
)

var ASTBridgeImpl ASTBridge

type ASTBridge interface {
	get_ast(filename *string) ASTInfo
	get_ast_snippet(source_file *string, snippet *string) ASTInfo
	get_ast_snippet_binary(source_file *string, snippet *string) ASTInfo
	import_ast(source_file *string, filename *string, params *EvaluateParams) ASTInfo
	evaluate_ast(ast_string *string, params *EvaluateParams) ASTInfo
	evaluate_snippet(filename *string, snippet *string, params *EvaluateParams) ASTInfo
	lint_snippet(filename *string, snippet *string, params *EvaluateParams) ASTInfo
	format_snippet(filename *string, snippet *string, options *FormatOptions) ASTInfo
	version() string
	get_test_objects() []TestData
}

//export CASTBridge_get_ast
func CASTBridge_get_ast(filename C.StringRef, slot *C.void, cb *C.void) {
	_new_filename := newString(filename)
	resp := ASTBridgeImpl.get_ast(&_new_filename)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_get_ast_snippet
func CASTBridge_get_ast_snippet(source_file C.StringRef, snippet C.StringRef, slot *C.void, cb *C.void) {
	_new_source_file := newString(source_file)
	_new_snippet := newString(snippet)
	resp := ASTBridgeImpl.get_ast_snippet(&_new_source_file, &_new_snippet)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_get_ast_snippet_binary
func CASTBridge_get_ast_snippet_binary(source_file C.StringRef, snippet C.StringRef, slot *C.void, cb *C.void) {
	_new_source_file := newString(source_file)
	_new_snippet := newString(snippet)
	resp := ASTBridgeImpl.get_ast_snippet_binary(&_new_source_file, &_new_snippet)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_import_ast
func CASTBridge_import_ast(source_file C.StringRef, filename C.StringRef, params C.EvaluateParamsRef, slot *C.void, cb *C.void) {
	_new_source_file := newString(source_file)
	_new_filename := newString(filename)
	_new_params := newEvaluateParams(params)
	resp := ASTBridgeImpl.import_ast(&_new_source_file, &_new_filename, &_new_params)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_evaluate_ast
func CASTBridge_evaluate_ast(ast_string C.StringRef, params C.EvaluateParamsRef, slot *C.void, cb *C.void) {
	_new_ast_string := newString(ast_string)
	_new_params := newEvaluateParams(params)
	resp := ASTBridgeImpl.evaluate_ast(&_new_ast_string, &_new_params)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_evaluate_snippet
func CASTBridge_evaluate_snippet(filename C.StringRef, snippet C.StringRef, params C.EvaluateParamsRef, slot *C.void, cb *C.void) {
	_new_filename := newString(filename)
	_new_snippet := newString(snippet)
	_new_params := newEvaluateParams(params)
	resp := ASTBridgeImpl.evaluate_snippet(&_new_filename, &_new_snippet, &_new_params)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_lint_snippet
func CASTBridge_lint_snippet(filename C.StringRef, snippet C.StringRef, params C.EvaluateParamsRef, slot *C.void, cb *C.void) {
	_new_filename := newString(filename)
	_new_snippet := newString(snippet)
	_new_params := newEvaluateParams(params)
	resp := ASTBridgeImpl.lint_snippet(&_new_filename, &_new_snippet, &_new_params)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_format_snippet
func CASTBridge_format_snippet(filename C.StringRef, snippet C.StringRef, options C.FormatOptionsRef, slot *C.void, cb *C.void) {
	_new_filename := newString(filename)
	_new_snippet := newString(snippet)
	_new_options := newFormatOptions(options)
	resp := ASTBridgeImpl.format_snippet(&_new_filename, &_new_snippet, &_new_options)
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_version
func CASTBridge_version(slot *C.void, cb *C.void) {
	resp := ASTBridgeImpl.version()
	resp_ref, buffer := cvt_ref(cntString, refString)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CASTBridge_get_test_objects
func CASTBridge_get_test_objects(slot *C.void, cb *C.void) {
	resp := ASTBridgeImpl.get_test_objects()
	resp_ref, buffer := cvt_ref(cnt_list_mapper(cntTestData), ref_list_mapper(refTestData))(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

var DebuggerBridgeImpl DebuggerBridge

type DebuggerBridge interface {
	step()
	step_over()
	continue_debugger()
	add_breakpoint(filename *string, line *int64, column *int64) StringInfo
	get_breakpoints() []string
	clear_breakpoints(filename *string)
	get_stack_trace() ASTInfo
	launch(filename *string, content *string, params *EvaluateParams)
	wait_for_event() ASTInfo
	list_vars() ASTInfo
	lookup_value(identifier *string) StringInfo
}

//export CDebuggerBridge_step
func CDebuggerBridge_step() {
	DebuggerBridgeImpl.step()
}

//export CDebuggerBridge_step_over
func CDebuggerBridge_step_over() {
	DebuggerBridgeImpl.step_over()
}

//export CDebuggerBridge_continue_debugger
func CDebuggerBridge_continue_debugger() {
	DebuggerBridgeImpl.continue_debugger()
}

//export CDebuggerBridge_add_breakpoint
func CDebuggerBridge_add_breakpoint(filename C.StringRef, line C.int64_t, column C.int64_t, slot *C.void, cb *C.void) {
	_new_filename := newString(filename)
	_new_line := newC_int64_t(line)
	_new_column := newC_int64_t(column)
	resp := DebuggerBridgeImpl.add_breakpoint(&_new_filename, &_new_line, &_new_column)
	resp_ref, buffer := cvt_ref(cntStringInfo, refStringInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CDebuggerBridge_get_breakpoints
func CDebuggerBridge_get_breakpoints(slot *C.void, cb *C.void) {
	resp := DebuggerBridgeImpl.get_breakpoints()
	resp_ref, buffer := cvt_ref(cnt_list_mapper(cntString), ref_list_mapper(refString))(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CDebuggerBridge_clear_breakpoints
func CDebuggerBridge_clear_breakpoints(filename C.StringRef) {
	_new_filename := newString(filename)
	DebuggerBridgeImpl.clear_breakpoints(&_new_filename)
}

//export CDebuggerBridge_get_stack_trace
func CDebuggerBridge_get_stack_trace(slot *C.void, cb *C.void) {
	resp := DebuggerBridgeImpl.get_stack_trace()
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CDebuggerBridge_launch
func CDebuggerBridge_launch(filename C.StringRef, content C.StringRef, params C.EvaluateParamsRef) {
	_new_filename := newString(filename)
	_new_content := newString(content)
	_new_params := newEvaluateParams(params)
	DebuggerBridgeImpl.launch(&_new_filename, &_new_content, &_new_params)
}

//export CDebuggerBridge_wait_for_event
func CDebuggerBridge_wait_for_event(slot *C.void, cb *C.void) {
	resp := DebuggerBridgeImpl.wait_for_event()
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CDebuggerBridge_list_vars
func CDebuggerBridge_list_vars(slot *C.void, cb *C.void) {
	resp := DebuggerBridgeImpl.list_vars()
	resp_ref, buffer := cvt_ref(cntASTInfo, refASTInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

//export CDebuggerBridge_lookup_value
func CDebuggerBridge_lookup_value(identifier C.StringRef, slot *C.void, cb *C.void) {
	_new_identifier := newString(identifier)
	resp := DebuggerBridgeImpl.lookup_value(&_new_identifier)
	resp_ref, buffer := cvt_ref(cntStringInfo, refStringInfo)(&resp)
	asmcall.CallFuncG0P2(unsafe.Pointer(cb), unsafe.Pointer(&resp_ref), unsafe.Pointer(slot))
	runtime.KeepAlive(resp_ref)
	runtime.KeepAlive(resp)
	runtime.KeepAlive(buffer)
}

func newString(s_ref C.StringRef) string {
	return unsafe.String((*byte)(unsafe.Pointer(s_ref.ptr)), s_ref.len)
}
func refString(s *string, _ *[]byte) C.StringRef {
	return C.StringRef{
		ptr: (*C.uint8_t)(unsafe.StringData(*s)),
		len: C.uintptr_t(len(*s)),
	}
}

func ownString(s_ref C.StringRef) string {
	return string(unsafe.Slice((*byte)(unsafe.Pointer(s_ref.ptr)), int(s_ref.len)))
}
func cntString(_ *string, _ *uint) [0]C.StringRef { return [0]C.StringRef{} }
func new_list_mapper[T1, T2 any](f func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		input := unsafe.Slice((*T1)(unsafe.Pointer(x.ptr)), x.len)
		output := make([]T2, len(input))
		for i, v := range input {
			output[i] = f(v)
		}
		return output
	}
}
func new_list_mapper_primitive[T1, T2 any](_ func(T1) T2) func(C.ListRef) []T2 {
	return func(x C.ListRef) []T2 {
		return unsafe.Slice((*T2)(unsafe.Pointer(x.ptr)), x.len)
	}
}

// only handle non-primitive type T
func cnt_list_mapper[T, R any](f func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef {
		for _, v := range *s {
			f(&v, cnt)
		}
		*cnt += uint(len(*s)) * size_of[R]()
		return [0]C.ListRef{}
	}
}

// only handle primitive type T
func cnt_list_mapper_primitive[T, R any](_ func(s *T, cnt *uint) [0]R) func(s *[]T, cnt *uint) [0]C.ListRef {
	return func(s *[]T, cnt *uint) [0]C.ListRef { return [0]C.ListRef{} }
}

// only handle non-primitive type T
func ref_list_mapper[T, R any](f func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*buffer) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(len(*s)),
			}
		}
		ret := C.ListRef{
			ptr: unsafe.Pointer(&(*buffer)[0]),
			len: C.uintptr_t(len(*s)),
		}
		children_bytes := int(size_of[R]()) * len(*s)
		children := (*buffer)[:children_bytes]
		*buffer = (*buffer)[children_bytes:]
		for _, v := range *s {
			child := f(&v, buffer)
			len := unsafe.Sizeof(child)
			copy(children, unsafe.Slice((*byte)(unsafe.Pointer(&child)), len))
			children = children[len:]
		}
		return ret
	}
}

// only handle primitive type T
func ref_list_mapper_primitive[T, R any](_ func(s *T, buffer *[]byte) R) func(s *[]T, buffer *[]byte) C.ListRef {
	return func(s *[]T, buffer *[]byte) C.ListRef {
		if len(*s) == 0 {
			return C.ListRef{
				ptr: unsafe.Pointer(nil),
				len: C.uintptr_t(0),
			}
		}
		return C.ListRef{
			ptr: unsafe.Pointer(&(*s)[0]),
			len: C.uintptr_t(len(*s)),
		}
	}
}
func size_of[T any]() uint {
	var t T
	return uint(unsafe.Sizeof(t))
}
func cvt_ref[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt)
		return ref_f(p, &buffer), buffer
	}
}
func cvt_ref_cap[R, CR any](cnt_f func(s *R, cnt *uint) [0]CR, ref_f func(p *R, buffer *[]byte) CR, add_cap uint) func(p *R) (CR, []byte) {
	return func(p *R) (CR, []byte) {
		var cnt uint
		cnt_f(p, &cnt)
		buffer := make([]byte, cnt, cnt+add_cap)
		return ref_f(p, &buffer), buffer
	}
}

func newC_uint8_t(n C.uint8_t) uint8    { return uint8(n) }
func newC_uint16_t(n C.uint16_t) uint16 { return uint16(n) }
func newC_uint32_t(n C.uint32_t) uint32 { return uint32(n) }
func newC_uint64_t(n C.uint64_t) uint64 { return uint64(n) }
func newC_int8_t(n C.int8_t) int8       { return int8(n) }
func newC_int16_t(n C.int16_t) int16    { return int16(n) }
func newC_int32_t(n C.int32_t) int32    { return int32(n) }
func newC_int64_t(n C.int64_t) int64    { return int64(n) }
func newC_bool(n C.bool) bool           { return bool(n) }
func newC_uintptr_t(n C.uintptr_t) uint { return uint(n) }
func newC_intptr_t(n C.intptr_t) int    { return int(n) }
func newC_float(n C.float) float32      { return float32(n) }
func newC_double(n C.double) float64    { return float64(n) }

func cntC_uint8_t(_ *uint8, _ *uint) [0]C.uint8_t    { return [0]C.uint8_t{} }
func cntC_uint16_t(_ *uint16, _ *uint) [0]C.uint16_t { return [0]C.uint16_t{} }
func cntC_uint32_t(_ *uint32, _ *uint) [0]C.uint32_t { return [0]C.uint32_t{} }
func cntC_uint64_t(_ *uint64, _ *uint) [0]C.uint64_t { return [0]C.uint64_t{} }
func cntC_int8_t(_ *int8, _ *uint) [0]C.int8_t       { return [0]C.int8_t{} }
func cntC_int16_t(_ *int16, _ *uint) [0]C.int16_t    { return [0]C.int16_t{} }
func cntC_int32_t(_ *int32, _ *uint) [0]C.int32_t    { return [0]C.int32_t{} }
func cntC_int64_t(_ *int64, _ *uint) [0]C.int64_t    { return [0]C.int64_t{} }
func cntC_bool(_ *bool, _ *uint) [0]C.bool           { return [0]C.bool{} }
func cntC_uintptr_t(_ *uint, _ *uint) [0]C.uintptr_t { return [0]C.uintptr_t{} }
func cntC_intptr_t(_ *int, _ *uint) [0]C.intptr_t    { return [0]C.intptr_t{} }
func cntC_float(_ *float32, _ *uint) [0]C.float      { return [0]C.float{} }
func cntC_double(_ *float64, _ *uint) [0]C.double    { return [0]C.double{} }

func refC_uint8_t(p *uint8, _ *[]byte) C.uint8_t    { return C.uint8_t(*p) }
func refC_uint16_t(p *uint16, _ *[]byte) C.uint16_t { return C.uint16_t(*p) }
func refC_uint32_t(p *uint32, _ *[]byte) C.uint32_t { return C.uint32_t(*p) }
func refC_uint64_t(p *uint64, _ *[]byte) C.uint64_t { return C.uint64_t(*p) }
func refC_int8_t(p *int8, _ *[]byte) C.int8_t       { return C.int8_t(*p) }
func refC_int16_t(p *int16, _ *[]byte) C.int16_t    { return C.int16_t(*p) }
func refC_int32_t(p *int32, _ *[]byte) C.int32_t    { return C.int32_t(*p) }
func refC_int64_t(p *int64, _ *[]byte) C.int64_t    { return C.int64_t(*p) }
func refC_bool(p *bool, _ *[]byte) C.bool           { return C.bool(*p) }
func refC_uintptr_t(p *uint, _ *[]byte) C.uintptr_t { return C.uintptr_t(*p) }
func refC_intptr_t(p *int, _ *[]byte) C.intptr_t    { return C.intptr_t(*p) }
func refC_float(p *float32, _ *[]byte) C.float      { return C.float(*p) }
func refC_double(p *float64, _ *[]byte) C.double    { return C.double(*p) }

type FormatOptions struct {
	indent                 int32
	max_blank_lines        int32
	string_style           int32
	comment_style          int32
	pretty_field_names     bool
	pad_arrays             bool
	pad_objects            bool
	sort_imports           bool
	use_implicit_plus      bool
	strip_everything       bool
	strip_comments         bool
	strip_all_but_comments bool
}

func newFormatOptions(p C.FormatOptionsRef) FormatOptions {
	return FormatOptions{
		indent:                 newC_int32_t(p.indent),
		max_blank_lines:        newC_int32_t(p.max_blank_lines),
		string_style:           newC_int32_t(p.string_style),
		comment_style:          newC_int32_t(p.comment_style),
		pretty_field_names:     newC_bool(p.pretty_field_names),
		pad_arrays:             newC_bool(p.pad_arrays),
		pad_objects:            newC_bool(p.pad_objects),
		sort_imports:           newC_bool(p.sort_imports),
		use_implicit_plus:      newC_bool(p.use_implicit_plus),
		strip_everything:       newC_bool(p.strip_everything),
		strip_comments:         newC_bool(p.strip_comments),
		strip_all_but_comments: newC_bool(p.strip_all_but_comments),
	}
}
func ownFormatOptions(p C.FormatOptionsRef) FormatOptions {
	return FormatOptions{
		indent:                 newC_int32_t(p.indent),
		max_blank_lines:        newC_int32_t(p.max_blank_lines),
		string_style:           newC_int32_t(p.string_style),
		comment_style:          newC_int32_t(p.comment_style),
		pretty_field_names:     newC_bool(p.pretty_field_names),
		pad_arrays:             newC_bool(p.pad_arrays),
		pad_objects:            newC_bool(p.pad_objects),
		sort_imports:           newC_bool(p.sort_imports),
		use_implicit_plus:      newC_bool(p.use_implicit_plus),
		strip_everything:       newC_bool(p.strip_everything),
		strip_comments:         newC_bool(p.strip_comments),
		strip_all_but_comments: newC_bool(p.strip_all_but_comments),
	}
}
func cntFormatOptions(s *FormatOptions, cnt *uint) [0]C.FormatOptionsRef {
	_ = s
	_ = cnt
	return [0]C.FormatOptionsRef{}
}
func refFormatOptions(p *FormatOptions, buffer *[]byte) C.FormatOptionsRef {
	return C.FormatOptionsRef{
		indent:                 refC_int32_t(&p.indent, buffer),
		max_blank_lines:        refC_int32_t(&p.max_blank_lines, buffer),
		string_style:           refC_int32_t(&p.string_style, buffer),
		comment_style:          refC_int32_t(&p.comment_style, buffer),
		pretty_field_names:     refC_bool(&p.pretty_field_names, buffer),
		pad_arrays:             refC_bool(&p.pad_arrays, buffer),
		pad_objects:            refC_bool(&p.pad_objects, buffer),
		sort_imports:           refC_bool(&p.sort_imports, buffer),
		use_implicit_plus:      refC_bool(&p.use_implicit_plus, buffer),
		strip_everything:       refC_bool(&p.strip_everything, buffer),
		strip_comments:         refC_bool(&p.strip_comments, buffer),
		strip_all_but_comments: refC_bool(&p.strip_all_but_comments, buffer),
	}
}

type ExtValue struct {
	name  string
	value string
}

func newExtValue(p C.ExtValueRef) ExtValue {
	return ExtValue{
		name:  newString(p.name),
		value: newString(p.value),
	}
}
func ownExtValue(p C.ExtValueRef) ExtValue {
	return ExtValue{
		name:  ownString(p.name),
		value: ownString(p.value),
	}
}
func cntExtValue(s *ExtValue, cnt *uint) [0]C.ExtValueRef {
	_ = s
	_ = cnt
	return [0]C.ExtValueRef{}
}
func refExtValue(p *ExtValue, buffer *[]byte) C.ExtValueRef {
	return C.ExtValueRef{
		name:  refString(&p.name, buffer),
		value: refString(&p.value, buffer),
	}
}

type ASTInfo struct {
	ast_data   []uint8
	error_data string
}

func newASTInfo(p C.ASTInfoRef) ASTInfo {
	return ASTInfo{
		ast_data:   new_list_mapper_primitive(newC_uint8_t)(p.ast_data),
		error_data: newString(p.error_data),
	}
}
func ownASTInfo(p C.ASTInfoRef) ASTInfo {
	return ASTInfo{
		ast_data:   new_list_mapper(newC_uint8_t)(p.ast_data),
		error_data: ownString(p.error_data),
	}
}
func cntASTInfo(s *ASTInfo, cnt *uint) [0]C.ASTInfoRef {
	_ = s
	_ = cnt
	return [0]C.ASTInfoRef{}
}
func refASTInfo(p *ASTInfo, buffer *[]byte) C.ASTInfoRef {
	return C.ASTInfoRef{
		ast_data:   ref_list_mapper_primitive(refC_uint8_t)(&p.ast_data, buffer),
		error_data: refString(&p.error_data, buffer),
	}
}

type StringInfo struct {
	data  string
	error string
}

func newStringInfo(p C.StringInfoRef) StringInfo {
	return StringInfo{
		data:  newString(p.data),
		error: newString(p.error),
	}
}
func ownStringInfo(p C.StringInfoRef) StringInfo {
	return StringInfo{
		data:  ownString(p.data),
		error: ownString(p.error),
	}
}
func cntStringInfo(s *StringInfo, cnt *uint) [0]C.StringInfoRef {
	_ = s
	_ = cnt
	return [0]C.StringInfoRef{}
}
func refStringInfo(p *StringInfo, buffer *[]byte) C.StringInfoRef {
	return C.StringInfoRef{
		data:  refString(&p.data, buffer),
		error: refString(&p.error, buffer),
	}
}

type EvaluateParams struct {
	ext_vars []ExtValue
	ext_code []ExtValue
	jpaths   []string
}

func newEvaluateParams(p C.EvaluateParamsRef) EvaluateParams {
	return EvaluateParams{
		ext_vars: new_list_mapper(newExtValue)(p.ext_vars),
		ext_code: new_list_mapper(newExtValue)(p.ext_code),
		jpaths:   new_list_mapper(newString)(p.jpaths),
	}
}
func ownEvaluateParams(p C.EvaluateParamsRef) EvaluateParams {
	return EvaluateParams{
		ext_vars: new_list_mapper(ownExtValue)(p.ext_vars),
		ext_code: new_list_mapper(ownExtValue)(p.ext_code),
		jpaths:   new_list_mapper(ownString)(p.jpaths),
	}
}
func cntEvaluateParams(s *EvaluateParams, cnt *uint) [0]C.EvaluateParamsRef {
	cnt_list_mapper(cntExtValue)(&s.ext_vars, cnt)
	cnt_list_mapper(cntExtValue)(&s.ext_code, cnt)
	cnt_list_mapper(cntString)(&s.jpaths, cnt)
	return [0]C.EvaluateParamsRef{}
}
func refEvaluateParams(p *EvaluateParams, buffer *[]byte) C.EvaluateParamsRef {
	return C.EvaluateParamsRef{
		ext_vars: ref_list_mapper(refExtValue)(&p.ext_vars, buffer),
		ext_code: ref_list_mapper(refExtValue)(&p.ext_code, buffer),
		jpaths:   ref_list_mapper(refString)(&p.jpaths, buffer),
	}
}

type TestData struct {
	name string
	data []uint8
}

func newTestData(p C.TestDataRef) TestData {
	return TestData{
		name: newString(p.name),
		data: new_list_mapper_primitive(newC_uint8_t)(p.data),
	}
}
func ownTestData(p C.TestDataRef) TestData {
	return TestData{
		name: ownString(p.name),
		data: new_list_mapper(newC_uint8_t)(p.data),
	}
}
func cntTestData(s *TestData, cnt *uint) [0]C.TestDataRef {
	_ = s
	_ = cnt
	return [0]C.TestDataRef{}
}
func refTestData(p *TestData, buffer *[]byte) C.TestDataRef {
	return C.TestDataRef{
		name: refString(&p.name, buffer),
		data: ref_list_mapper_primitive(refC_uint8_t)(&p.data, buffer),
	}
}
func main() {}
