[package]
name = "language-server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true, features = ["proposed"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
pretty_assertions = { workspace = true }
log = { workspace = true }
ropey = { workspace = true }
similar = "3.0.0"
# For better external library support
tree-sitter = ">=0.22.6"
crossbeam = { workspace = true }
rand = "0.10.0"
mockall = "0.14.0"
utils = { path = "../utils"}
rayon.workspace = true
