[package]
name = "jsonnet-cst"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tree-sitter = { workspace = true }
tree-sitter-jsonnet = {git = "https://github.com/koskev/tree-sitter-jsonnet"}
jsonnet-location = { path = "../jsonnet-location"}
ropey = { workspace = true }
log = { workspace = true }
utils.workspace = true
