[package]
name = "jsonnet-location"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bincode = { workspace = true }
lsp-types = { workspace = true, features = ["proposed"] }
serde = { workspace = true, features = ["derive", "rc"] }
tree-sitter = { workspace = true }
language-server = { path = "../language-server"}
anyhow.workspace = true
