[package]
name = "grustonnet-ls-lib"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
tracing = ["tracy-client"]

[dependencies]
anyhow = { workspace = true }
lazy_static = "1.5.0"
lsp-server = { workspace = true }
lsp-types = { workspace = true, features = ["proposed"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
name-variant = { path = "../name-variant"}
jsonnet-bridge = { path = "../jsonnet-bridge"}
jsonnet-location = { path = "../jsonnet-location"}
jsonnet-cst = { path = "../jsonnet-cst"}
grustonnet-node = { path = "../grustonnet-node"}
grustonnet-config = { path = "../grustonnet-config"}
language-server = { path = "../language-server"}
utils = { path = "../utils"}
paste = { package = "pastey", version = "0.2.3" }
ropey = { workspace = true }
regex = { workspace = true }
tree-sitter = { workspace = true }
pretty_assertions = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
schemars = { workspace = true }
jsonnet-std-docs = { path = "../jsonnet-std-docs"}
test-macros = { path = "../test-macros"}
strum = { version = "0.28.0", features = ["derive", "strum_macros"] }
walkdir = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
tracy-client = { workspace = true, optional = true }
thiserror = "2.0.12"
rmp-serde = "1.3.0"
bincode-next = { workspace = true }
assert_unordered = "0.4.0"
semver = "1.0.27"
fallible-iterator = "0.3.0"
stacker = "0.1.23"
tree-sitter-jsonnet = {git = "https://github.com/koskev/tree-sitter-jsonnet"}

[build-dependencies]
ureq = "3.3.0"
jsonnet-bridge = { path = "../jsonnet-bridge"}
jsonnet-std-docs = { path = "../jsonnet-std-docs"}
htmd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rmp-serde = "1.3.0"
sha2 = "0.11.0"
