[package]
name = "grustonnet-lint"
edition = "2024"

[lints]
workspace = true

[features]
tracing = ["tracy-client", "grustonnet-ls-lib/tracing"]

[dependencies]
anyhow = { workspace = true }
rust2go-env = { path = "../rust2go-env"}
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
env_logger = { workspace = true }
log.workspace = true
rayon.workspace = true
grustonnet-ls-lib = { path = "../grustonnet-ls-lib"}
language-server = { path = "../language-server"}
utils = { path = "../utils"}
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tracy-client = { workspace = true, optional = true }
lsp-types = { workspace = true, features = ["proposed"] }
miette = { version = "7.6.0", features = ["fancy"] }
ropey = { workspace = true }
glob = "0.3.3"
[target.'cfg(unix)'.dependencies]
exec = { version = "0.3.1" }

[[bin]]
name = "grustonnet-lint"
path = "src/main.rs"
