on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --current
        env:
          OUTPUT: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md
          retention-days: 1
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          # XXX: Since windows is such a bad system, we just cross compile it from Linux
          - os-name: Windows-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-pc-windows-gnu

          - os-name: macOS-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    needs: changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Version
        run: |
          GITHUB_TAG_NAME=${{ github.ref_name }}
          TAG_NAME=${GITHUB_TAG_NAME:-v0.0.0}
          TAG_VERSION=${TAG_NAME:1}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
      - name: Generate output name
        run: |
          RELEASE_TAR=$(echo "grustonnet_${{ matrix.platform.os-name }}.tar.gz" | tr '[:upper:]' '[:lower:]' | tr '-' '_')
          echo ${RELEASE_TAR}
          echo "RELEASE_TAR=${RELEASE_TAR}" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Set Cargo Version
        run: |
          # TODO: Suffix handling (e.g. -RC1)
          cargo install cargo-set-version
          echo "Setting program version to ${TAG_VERSION}"
          cargo set-version ${TAG_VERSION}
      - name: Get changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog
          path: changelog
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Install cross compile tools
        if: ${{ contains(matrix.platform.target, 'windows') && contains(matrix.platform.runs-on, 'ubuntu') }}
        run: sudo apt update && sudo apt install gcc-mingw-w64 && rustup target add x86_64-pc-windows-gnu
      - name: Build binary
        run: make build-${{ matrix.platform.target }}
        env:
          RUST_BACKTRACE: 1
          GODEBUG: "invalidptr=0,cgocheck=0"
      - name: Compress binary
        run: |
          tmpdir=$(mktemp -d)
          # Mac is stupid so we can't use transform in tar nor -executable in find
          find ./ -type f -perm -111 -iname "grustonnet-*" -exec cp {} "$tmpdir/" \;
          # Stupid but makes sure it works everywhere
          pushd "$tmpdir"
          tar -czf "$RELEASE_TAR" *
          popd
          mv "$tmpdir"/"$RELEASE_TAR" ./
          rm -rf "$tmpdir"
      - name: Publish artifacts and release
        uses:  softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_TAR }}
          body_path: changelog/CHANGELOG.md
