name: Test Windows GNU

on:
  push:
  pull_request:

jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Test Windows x86_64 GNU
         uses: Reloaded-Project/devops-rust-test-in-latest-wine@v1
         env:
           RUSTFLAGS: ""
         with:
           rust-project-path: '.'
           target: 'x86_64-pc-windows-gnu'
