name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          # XXX: Since windows is such a bad system, we just cross compile it from Linux and use wine
          - os-name: Windows-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-pc-windows-gnu

          - os-name: macOS-arm64
            runs-on: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - name: Install nightly rust
      run: rustup toolchain install nightly && rustup default nightly
    - name: Install Rust test dependencies
      run: cargo install --root . cargo2junit cargo-tarpaulin
    - name: Run tests
      run: bin/cargo-tarpaulin --tests --out xml --engine llvm -- -Z unstable-options --format=json | bin/cargo2junit > report.xml
      if: ${{ !contains(matrix.platform.target, 'windows') }}
      env:
        GODEBUG: "invalidptr=0,cgocheck=0"
        RUST_BACKTRACE: 1
    - name: Test Summary
      uses: test-summary/action@v2
      if: ${{ !contains(matrix.platform.target, 'windows') }}
      with:
        paths: "report.xml"
    - name: Test Windows x86_64 GNU
      uses: Reloaded-Project/devops-rust-test-in-latest-wine@v1
      if: ${{ contains(matrix.platform.target, 'windows') }}
      env:
        RUSTFLAGS: ""
      with:
        rust-project-path: '.'
        target: 'x86_64-pc-windows-gnu'
